version: '3.4'
services:
  app:
    build: .
    environment:
      NODE_ENV: "${NODE_ENV}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - ./:/app
    networks:
      - appnet
networks:
  appnet:
    driver: bridge